location = /kol {
    proxy_pass http://127.0.0.1:13010;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Prefix /kol;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location ^~ /kol/api/ {
    proxy_pass http://127.0.0.1:18010/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Prefix /kol;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location ^~ /kol/ {
    proxy_pass http://127.0.0.1:13010;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Prefix /kol;
    proxy_set_header X-Forwarded-Proto $scheme;
}
